#!/usr/bin/env python

##### Time Series of Air Quality Simulations: (VAR) Daily Average over the Month (no shipping case) COMBINE_ACONC files
# Filler VAR is SO2.

import matplotlib.pyplot as plt; import numpy as np; import netCDF4; from netCDF4 import Dataset
import pandas as pd; import numpy.ma as ma; import time as timeit; import os; import math
import itertools

# -----------------------------------------------------
# Single daily file (hourly sums over the entire grid)
sample = '/projects/b1045/wrf-cmaq/output/Chicago_LADCO/output_Cassia_noCMV_4km_sf_rrtmg_10_8_1_v3852/postprocess/COMBINE_ACONC_20180809.nc'
sampleread = Dataset(sample,mode='r')
specified = sampleread.variables['SO2']

totalgridsumperhour = []

for i in range(0,24):
    day_var_sum = specifiedtime[i,0,:,:]
    sumovergrid = np.concatenate(day_var_sum).sum()
    totalgridsumperhour.append(sumovergrid)   
# print(totalgridsumperhour)

plt.plot(range(0,24), totalgridsumperhour, 'o-')
plt.title('Hourly SO2 Concentrations for 2018/08/09', size = 15)
plt.ylabel(' SO2 concentration (ppbV) ', size = 12, rotation=90)
plt.xlabel(' Hour ', size = 12, rotation=0)
plt.show()

#QUESTION: What does hour 0 mean? What timezone is being used?
# -----------------------------------------------------
